import 'public/assets/css/common.module.scss';
import 'public/assets/css/common.css';
import localFont from 'next/font/local';
import Link from "next/link";
import Header from "@/components/Header/Header";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const covered = localFont({
    src: [
        {
            path : '../public/assets/font/coveredByYourGrace.woff',
            weight : '400',
        },
    ]
})

const pretendard = localFont({
    src: [
        {
            path : '../public/assets/font/Pretendard-Regular.woff',
            weight : '400',
        },
        {
            path : '../public/assets/font/Pretendard-Medium.woff',
            weight : '500',
        },
        {
            path : '../public/assets/font/Pretendard-Bold.woff',
            weight : '700',
        },
    ]
})

const stolzl = localFont({
    src: [
        {
            path : '../public/assets/font/stolzl-Regular.woff',
            weight : '400',
        },
        {
            path : '../public/assets/font/Stolzl-Medium.woff',
            weight : '500',
        },
        {
            path : '../public/assets/font/Stolzl-Bold.woff',
            weight : '700',
        },
    ]
})

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={`${covered.className} ${pretendard.className} ${stolzl.className}`}>
        <body>
          {children}
        </body>
    </html>
  )
}
