import Image from 'next/image'
// import Header from "@/components/Header/Header";
import Link from "next/link";
import "./scss/main.scss";
import {initHelper} from "@/helper/init-helper";
const {jquery , variables} = initHelper();
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  // $(function(){
  //   alert();
  // });
  return (
   <>
     {/*<Header />*/}
     <Link href="guide" className="name-is-cha" style={{lineHeight: "10px"}}>guide</Link><br/>
     <Link href="pages/about">about</Link> <br/> <br/>

     <p className="text">mediaQuery type - </p> <br/> <br/>

     <Link href="guide/test/chchaa">chchaa test page</Link> <br/>
     <Link href="guide/test/jueun">jueun test page</Link> <br/>
     <Link href="guide/test/mijeong">mijeong test page</Link>

   </>
  )
}
